# Generated by Django 5.2.1 on 2025-05-23 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_Achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
