# Generated by Django 5.2.1 on 2025-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_achat_date_achat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_superviseur',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='alert_quantity',
            field=models.PositiveIntegerField(default=5, help_text='Threshold for low stock notification.', verbose_name='Alert Quantity'),
        ),
    ]
