# Generated by Django 5.2.1 on 2025-05-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_superviseur_produit_alert_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='alert_quantity',
            new_name='alert_quantite',
        ),
    ]
