# Generated by Django 5.2.1 on 2025-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_alert_quantity_produit_alert_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='alert_quantite',
            field=models.PositiveIntegerField(help_text='Seuil pour la notification de stock faible.', verbose_name='Alert Quantite'),
        ),
    ]
